include: package:flutter_lints/flutter.yaml

linter:
  rules:

formatter:
  trailing_commas: preserve
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
