// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2l6DIIAFoGaBfs2Lv3oqSZQjFsXDssU',
    appId: '1:361962358853:web:233a747d9c331bd94cfb2c',
    messagingSenderId: '361962358853',
    projectId: 'flutter-study-2188c',
    authDomain: 'flutter-study-2188c.firebaseapp.com',
    databaseURL: 'https://flutter-study-2188c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-study-2188c.firebasestorage.app',
    measurementId: 'G-FQHYRYFQZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXkPPe2-cWILW9qdtWaJ62OHSmPfffTc',
    appId: '1:361962358853:android:01877bc5adfd9c034cfb2c',
    messagingSenderId: '361962358853',
    projectId: 'flutter-study-2188c',
    databaseURL: 'https://flutter-study-2188c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-study-2188c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNFuCwTCU57K1T_V6CrmZ3BEIQmPIWIU',
    appId: '1:361962358853:ios:c83b4dbe447f28254cfb2c',
    messagingSenderId: '361962358853',
    projectId: 'flutter-study-2188c',
    databaseURL: 'https://flutter-study-2188c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-study-2188c.firebasestorage.app',
    iosBundleId: 'com.example.section09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpNFuCwTCU57K1T_V6CrmZ3BEIQmPIWIU',
    appId: '1:361962358853:ios:c83b4dbe447f28254cfb2c',
    messagingSenderId: '361962358853',
    projectId: 'flutter-study-2188c',
    databaseURL: 'https://flutter-study-2188c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-study-2188c.firebasestorage.app',
    iosBundleId: 'com.example.section09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX2l6DIIAFoGaBfs2Lv3oqSZQjFsXDssU',
    appId: '1:361962358853:web:96fc3efdd9a48d0c4cfb2c',
    messagingSenderId: '361962358853',
    projectId: 'flutter-study-2188c',
    authDomain: 'flutter-study-2188c.firebaseapp.com',
    databaseURL: 'https://flutter-study-2188c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-study-2188c.firebasestorage.app',
    measurementId: 'G-WVPFFBYR86',
  );
}
